name: "StackState Sensor API - Push Scala"

on:
  release:
      types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
          java-version: 1.11
    - name: Generate protoc
      uses: docker://ghcr.io/stackvista/scalapb
      with:
        args: -b /github/workspace -z generated/scala -i protobuf/Sensor.proto -o generated/scala
    - name: Push jar to artifactory
      run: ./gradlew clean build artifactoryPublish
      env:
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

